language: csharp
mono: none
dotnet: 2.2.301
solution: ArchUnit.sln
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release --output nupkgs -p:PackageVersion=0.1.0-draft-1
  - dotnet test -c Release
    
deploy:
  provider: script
  script: dotnet nuget push ./ArchUnitNET/nupkgs/TngTech.ArchUnitNET.*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    tags: true