language: csharp
mono: none
dotnet: 2.2.301
solution: ArchUnit.sln
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release --output nupkgs -p:PackageVersion=0.1.0-draft-4
  - dotnet test -c Release
    
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./Deploy/deploy.sh && ./Deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    tags: true
    all_branches: true